spring:
  application:
    name: saas-cobranca
    
  datasource:
    url: jdbc:postgresql://localhost:5432/cobranca_db
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    # Como vamos usar o Flyway para criar as tabelas, o Hibernate não deve criar nada, apenas validar
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    # O Flyway vai rodar os scripts da pasta db/migration automaticamente
    locations: classpath:db/migration/public
    baseline-on-migrate: true

server:
  port: 8080

api:
  security:
    rotas-publicas:
      - /api/auth/login
      - /v3/api-docs
      - /swagger-ui
      - /swagger-ui.html